### ISSUE TITLE
SymbolCollector.Console fails to run on macOS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/symbol-collector#114]
Since the .NET 5 upgrade the self contained exectuable for macOS fails to run:

```
./SymbolCollector.Console
Error:
  An assembly specified in the application dependencies manifest (SymbolCollector.Console.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.osx-x64', version: '5.0.3'
    path: 'libSystem.IO.Compression.Native.dylib'
```

Latest [version that works is 1.2.1](https://github.com/getsentry/symbol-collector/releases/tag/1.2.1).
Breakage happened when upgrading to .NET 5.0

Run CLI `--version` after build as a "smoke-test"
Something like:

```
# Smoke test the native console app is compatible platform:

if macos; then
cli=./publish-osx-x64/SymbolCollector.Console
chmod +x $cli
./$cli
```

**Comment by lucas-zimerman** [comment]
Happens because it requires the additional dylib files that were generated on the OSX folder to be "shipped" with SymbolCollector.Console. 
Not sure why this specific published path doesn't glue everything together like the others.

**Comment by bruno-garcia** [comment]
> Happens because it requires the additional dylib files that were generated on the OSX folder to be "shipped" with SymbolCollector.Console.
> Not sure why this specific published path doesn't glue everything together like the others.

This was a regression added on 5.0? 
I mean the point of single file distribution is to have a single file. I would expect any native dependency to be bundled in the final artifact (which is anyway extracted when it's first executed)
