### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/symbol-collector#131]
- [x] Upload native symbols through Craft + Symbol Collector (verify: https://github.com/getsentry/symbol-collector/pull/133)
- [x] Add second test to relaunch the app on the device in case the first test (symbol upload) crashes (verify: https://github.com/getsentry/symbol-collector/pull/134)
- [ ] Update craft with latest version
- [x] Add a transaction to CLI client
- [x] Bundle sources in pdb and get source context `EmbedAllSources` (https://github.com/getsentry/symbol-collector/commit/9f382c7cfbcc3e06fe8c02414c18ddfd49b800fa)
- [ ] Automatically collect from emulators. 
- [ ] Make sure device count and batch end counts match
- [ ] Codecov integration - Show coverage data on stack traces in Sentry
- https://github.com/getsentry/sentry/discussions/43826
- [ ] Make sure all assemblies upload coverage to codecov ([only Core is](https://app.codecov.io/gh/getsentry/symbol-collector/tree/master/src))
- [ ] HEAD request to check for symbol should hit GCS to spare the upload if symbol exists
- [ ] Build local cache of known debug ids
- [ ] Client should batch these check API calls instead of hitting for each file
- [ ] Can we capture crashes?

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
