### ISSUE TITLE
CLI windows client

### ISSUE THREAD

**Issue by vaind** [getsentry/symbol-collector#163]
It would be nice if there was a GH release artifact with a Windows CLI client. This is a low-prio though because it's easy to use WSL2 instead.

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
