### ISSUE TITLE
Tons of OOM. Metrics API could be the cause?

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/symbol-collector#195]
Groups pretty badly. Should it all group together? Probably not but not sure how to improve this

https://sentry.sentry.io/issues/?project=1886021&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+OutOfMemory&referrer=issue-list&statsPeriod=7d

![image](https://github.com/getsentry/symbol-collector/assets/1633368/6aaa83ee-1ede-4da8-ae48-25e048d07414)

Relates to:
* https://github.com/getsentry/sentry-dotnet/issues/3315

fyi @bitsandfoxes @jamescrosswell

**Comment by bruno-garcia** [comment]
Looks like it started after the last release:

https://sentry.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1886021&query=message%3AOutOfMemory&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29

![image](https://github.com/getsentry/symbol-collector/assets/1633368/5a80ce3b-38e6-45e6-bc99-ecc386be2948)

**Comment by jamescrosswell** [comment]
> https://sentry.sentry.io/issues/?project=1886021&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+OutOfMemory&referrer=issue-list&statsPeriod=7d

I don't seem to have access to that project. It requires login with Google and only allows certain domains, so assume it's Sentry employees only. 

The last release included these two changes - I can't see how either of them would cause an OOM exception though:
- https://github.com/getsentry/sentry-dotnet/pull/3281
- https://github.com/getsentry/sentry-dotnet/pull/3276

**Comment by bruno-garcia** [comment]
I gotta bump the version here and release

**Comment by bruno-garcia** [comment]
Might be fixed. There was the profiling mem leak fixed. And metrics is gone. Server also got more ram as it was getting over the limit often.

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
