### ISSUE TITLE
Lookup on paths /etc/ld.so.conf

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/symbol-collector#88]
Add all paths contained in `/etc/ld.so.conf` to `device` upload mode.

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
